### ISSUE TITLE
FBX SDK 2015 download?

### ISSUE THREAD

**Issue by yomomano** [arcanedreams/ArcManagedFBX#1]
Seems ADESK removed the 2015 SDK. Somebody has a copy for me? Thanks!

**Comment by LoveDuckie** [comment]
@yomomano I am going to try to find some time to upgrade it to the latest version of the SDK this weekend.

**Comment by yomomano** [comment]
that would be excellent!

**Comment by yomomano** [comment]
managed to compile it with SDK 2016.1.1 ! No changes needed.
