### ISSUE TITLE
Needs to be updated for VS 2017+

### ISSUE THREAD

**Issue by Cosmas47** [arcanedreams/ArcManagedFBX#5]
Leaving an arbitrary note here for this library. Still has great use but it won't compile out of the box in VS2017. Nor is the 2015 FBX SDK available. :(

**Comment by LoveDuckie** [comment]
@Cosmas47 It's nice to see that people are still using this, although I have to warn you that I am not actively supporting it right now!

I've taken a look at the Autodesk website, and I've noticed that they have an SDK for 2019 but with no support for Visual Studio 2017.

With that being said, you should still be able to compile using the Visual Studio 2017 VC++ compiler toolset, [as there should be no ABI differences between the compiled output from 2015 and 2017](https://blogs.msdn.microsoft.com/vcblog/2017/03/07/binary-compatibility-and-pain-free-upgrade-why-moving-to-visual-studio-2017-is-almost-too-easy/). This means that you can get the SDK targeted for 2015, and use it with your Visual Studio 2017 environment.

I haven't found the time to upgrade the library to the 2019 SDK just yet. It's something on my list of things to take care of.

**Comment by Cosmas47** [comment]
Perfect! Changed the target platform and it worked.
