### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by Cosmas47** [arcanedreams/ArcManagedFBX#6]
Do you have any sample files of writing an FBX back from scratch?

**Comment by mikeoverbay** [comment]
Look in the source for modFBX.vb
It contains all the FBX code to write and read that Im using with the wrapper.

**Comment by LoveDuckie** [comment]
> Look in the source for modFBX.vb
> It contains all the FBX code to write and read that Im using with the wrapper.

Where is this file? Not sure which one you are talking about. Can't find in repository.

**Comment by mikeoverbay** [comment]
Im sorry.. It was very late and I was confused about where this post originated.
Its in my repo for TankExporter.

**Comment by mikeoverbay** [comment]
Also.. my code uses a different FBX naming structure than this one.
Have you tried AutoDesks community?
http://forums.autodesk.com/t5/fbx-sdk/bd-p/area-b64
